### ISSUE TITLE
Open file manager when opening a directory

### ISSUE THREAD

**Issue by scls19fr** [NicolaiSoeborg/filemanager-plugin#39] opened 2018-10-11 07:30 UTC
Hello,

it will be a nice improvement if file manager start when opening a directory using `micro`.

## Current behavior
```
$ micro --version
Version: 1.4.1
Commit hash: 1856891
Compiled on August 10, 2018
$ micro .
. is a directory

Press enter to continue
```

## Expected behavior
```
$ micro .
```
should open file manager

Kind regards

PS: related issue #32

**Comment by sum01** [comment] 2018-10-11 15:41
Duplicate of https://github.com/NicolaiSoeborg/filemanager-plugin/issues/32

**Closed by sum01** 2018-10-11 15:41 UTC

**Comment by scls19fr** [comment] 2018-10-11 15:48
Sorry @sum01 , but I won't say that's a really a duplicate of #32 .

I think running simply:

```
micro
```

shouldn't open file manager but should still open a blank buffer for a new file 

but running


```
micro .
```
(or any other directory)

should open file manager

**Comment by sum01** [comment] 2018-10-11 16:20
I don't think I have any control over that. `micro .` isn't even a valid command.
