### ISSUE TITLE
Open file in new tab

### ISSUE THREAD

**Issue by sc0ttj** [NicolaiSoeborg/filemanager-plugin#34] opened 2018-09-02 14:03 UTC
https://github.com/NicolaiSoeborg/filemanager-plugin/blob/57df3ff47841916587986beaecace2295970a0f0/filemanager.lua#L553

How would I change the above behaviour to make the 'tree' plugin open the chosen file in a new tab, and switch to that tab, with the 'tree' plugin being already open in the newly created tab?

**Comment by sum01** [comment] 2018-09-02 17:03
I have no idea. I've already tried and it didn't work. Maybe there's a way to do it now, but I haven't been keeping up with Micro's changes.

Closing as duplicate of https://github.com/NicolaiSoeborg/filemanager-plugin/issues/26

**Closed by sum01** 2018-09-02 17:03 UTC
Labels: duplicate
